import { useState } from "react";
import { ArrowLeft, Play, ShieldAlert, TestTube2 } from "lucide-react";
import type { DesktopYacangPreview } from "@lxe/desktop-protocol";

const examples = ["我想看看最近一个月各仓卖得怎么样", "导出 MY8801 的月度销量", "月底各仓还剩多少库存", "这些产品什么时候入库和上架"];
const asText = (value: unknown): string => typeof value === "string" ? value : "";
const asRecords = (value: unknown): Record<string, unknown>[] => Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item)) : [];

export function YacangNaturalLanguageTestView({ onBack }: { onBack: () => void }) {
  const [requestText, setRequestText] = useState(""); const [preview, setPreview] = useState<DesktopYacangPreview | null>(null); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const plan = preview?.plan as Record<string, unknown> | undefined; const needsClarification = plan?.requires_clarification === true;
  async function previewRequest() { if (!requestText.trim() || !window.lxe?.desktop) return; setBusy(true); setError(""); setResult(null); setConfirmed(false); try { setPreview(await window.lxe.desktop.previewYacangExport({ request_text: requestText })); } catch (cause) { setPreview(null); setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  async function execute() { if (!preview || !confirmed || !window.lxe?.desktop) return; setBusy(true); setError(""); try { setResult((await window.lxe.desktop.executeYacangExport({ preview_id: asText(preview.preview_id), confirmed: true })).result); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  return <section className="workbench-page yacang-test-page" aria-labelledby="yacang-test-title"><header className="workbench-header"><div><button className="workbench-back" onClick={onBack} type="button"><ArrowLeft size={14}/>返回工作台</button><span>雅仓测试</span><h2 id="yacang-test-title">雅仓自然语言测试</h2><p>输入一句业务需求，查看确定性意图和执行计划。</p></div><div className="workbench-keyword"><TestTube2 size={15}/><code>preview-first</code></div></header>{error ? <div className="dashboard-query-notice" role="alert">{error}</div> : null}<section className="workbench-card"><label className="yacang-test-label" htmlFor="yacang-request">雅仓自然语言请求</label><textarea id="yacang-request" value={requestText} onChange={event => setRequestText(event.target.value)} placeholder="例如：我想看看最近一个月各仓卖得怎么样" rows={5}/><div className="yacang-test-examples">{examples.map(example => <button key={example} onClick={() => setRequestText(example)} type="button">{example}</button>)}</div><button className="workbench-primary-button" disabled={!requestText.trim() || busy} onClick={previewRequest} type="button"><TestTube2 size={17}/>{busy ? "解析中…" : "解析并预览"}</button></section>{plan ? <section className="workbench-card"><h3>流程预览</h3><p>执行日期：{asText(plan.execution_date)} · 逻辑任务：{asRecords(plan.logical_tasks).length} · 物理获取：{asRecords(plan.source_fetches).length}</p><pre className="yacang-test-json">{JSON.stringify(plan, null, 2)}</pre>{needsClarification ? <div className="workbench-platform-notice"><ShieldAlert size={20}/><div><strong>需要补充信息</strong><p>{asRecords(plan.questions).map(question => asText(question.message)).join("；")}</p></div></div> : <><label className="workbench-checkbox"><input checked={confirmed} onChange={event => setConfirmed(event.target.checked)} type="checkbox"/><span>我已核对以上范围，并确认执行真实雅仓导出。</span></label><button className="workbench-primary-button" disabled={!confirmed || busy} onClick={execute} type="button"><Play size={17}/>{busy ? "执行中…" : "确认并执行导出"}</button></>}</section> : null}{result ? <section className="workbench-card"><h3>执行结果：{asText(result.overall_status)}</h3><pre className="yacang-test-json">{JSON.stringify(result, null, 2)}</pre></section> : null}</section>;
}
